export * from './dashboard/dashboard-feedback.component'
export * from './feedback.create/feedback-create.component'
export * from './dashboard/cards/cards.components/cards.component'
export * from './dashboard/charts/charts.components/hospitality/chart-hospitality.component'
export * from './dashboard/charts/charts.components/clinical/chart-clinical.component'
export * from './clinic/clinic-list.component'