export * from './components/main.review/main-review.component'
export * from './components/patient.review/patient-review.component'
export * from './components/good.review/good-review.component'
export * from './components/improve.review/improve-review.component'
export * from './components/patient.submition/patient-submition.component'
export * from './pateint-review.module'